export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAILURE = "GET_WATCHLIST_FAILURE";

export const ADD_TO_WATCHLIST_REQUEST = "ADD_TO_WATCHLIST_REQUEST";
export const ADD_TO_WATCHLIST_SUCCESS = "ADD_TO_WATCHLIST_SUCCESS";
export const ADD_TO_WATCHLIST_FAILURE = "ADD_TO_WATCHLIST_FAILURE";

export const REMOVE_FROM_WATCHLIST_REQUEST = "REMOVE_FROM_WATCHLIST_REQUEST";
export const REMOVE_FROM_WATCHLIST_SUCCESS = "REMOVE_FROM_WATCHLIST_SUCCESS";
export const REMOVE_FROM_WATCHLIST_FAILURE = "REMOVE_FROM_WATCHLIST_FAILURE";

export const GET_ALL_LIST_REQUEST = "GET_ALL_LIST_REQUEST";
export const GET_ALL_LIST_SUCCESS = "GET_ALL_LIST_SUCCESS";
export const GET_ALL_LIST_FAILURE = "GET_ALL_LIST_FAILURE";

export const ADD_NEW_LIST_REQUEST = "ADD_NEW_LIST_REQUEST";
export const ADD_NEW_LIST_SUCCESS = "ADD_NEW_LIST_SUCCESS";
export const ADD_NEW_LIST_FAILURE = "ADD_NEW_LIST_FAILURE";

export const REMOVE_LIST_REQUEST = "REMOVE_LIST_REQUEST";
export const REMOVE_LIST_SUCCESS = "REMOVE_LIST_SUCCESS";
export const REMOVE_LIST_FAILURE = "REMOVE_LIST_FAILURE";

export const ADD_MOVIE_TO_LIST_REQUEST = "ADD_MOVIE_TO_LIST_REQUEST";
export const ADD_MOVIE_TO_LIST_SUCCESS = "ADD_MOVIE_TO_LIST_SUCCESS";
export const ADD_MOVIE_TO_LIST_FAILURE = "ADD_MOVIE_TO_LIST_FAILURE";
